from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from workflow_engine.application.contracts import CreateWorkflowCommand
from workflow_engine.domain.definitions import ApprovalWorkflowDefinition, SavedApprovalDefinition, WorkflowDefinition
from workflow_engine.domain.workflow import WorkflowEvent, WorkflowExecution


class WorkflowRepository(Protocol):
    def save_definition(self, definition: ApprovalWorkflowDefinition) -> SavedApprovalDefinition: ...
    def get_definition(self, definition_id: int) -> SavedApprovalDefinition: ...
    def list_definitions(self) -> list[SavedApprovalDefinition]: ...
    def create(self, definition: WorkflowDefinition, command: CreateWorkflowCommand) -> WorkflowExecution: ...
    def get(self, instance_id: int) -> WorkflowExecution: ...
    def list(self) -> list[WorkflowExecution]: ...
    def events(self, instance_id: int) -> list[WorkflowEvent]: ...
    def save(self, workflow: WorkflowExecution) -> None: ...


class UnitOfWork(Protocol):
    workflows: WorkflowRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, error_type, error, traceback) -> None: ...


UnitOfWorkFactory = Callable[[bool], UnitOfWork]